version: '2'

services:
  cron:
    container_name: test-cron
    build: .

    #only commands with the prefix "CONTAINER_" prefix will be copied to the crontab
    environment:
      - CONTAINER_test1=*/1 * * * * echo "start docker test" && docker start test  && echo "test done"

    # if you don't use the docker command you should remove the docker.sock from the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
